### ISSUE TITLE
Checking for <pre> breaks page

### ISSUE THREAD

**Issue by ncadigan** [sal0max/grav-plugin-shortcode-gallery-plusplus#4] opened 2021-02-10 21:50 UTC
commit 20de20970645f5fa6adcfa512ac6fd57bebea758 "Improved image parsing"

Below code breaks page

`            // check validity
            if (str_contains($content, "<pre>"))
                return "<p style='color: #d40000; font-weight: bold; padding: 1rem 0;'>[Shortcode Gallery++] Error:<br> 
                        &gt; Images provided got parsed as code block.<br>
                        &gt; Please check your markdown file and make sure the images aren't indented by tab or more than three spaces.</p>";`

Used example code in readme (switching out for my images). 
There is no \<pre\> anywhere on the page.

Error:
`Call to undefined function Grav\Plugin\Shortcodes\str_contains()`
References line 45

Removing the check validity makes it work fine.

**Comment by sal0max** [comment] 2021-02-10 23:10
Thanks for the bug report.

However, this is a duplicate of #3 
It's already fixed in Version 1.0.3

**Closed** 2021-02-10 23:11 UTC
Labels: duplicate
