### ISSUE TITLE
Light area at the bottom of the image on smartphone, horizontal screen

### ISSUE THREAD

**Issue by Fazarel** [sal0max/grav-plugin-shortcode-gallery-plusplus#13] opened 2021-07-09 21:03 UTC
On a cell phone, when the screen is rotated horizontally, a gray filter is applied to the image but not to the full height, leaving a lighter area at the bottom of the image.

Bug found on iPhone, Android, Ubports, with Firefox, Safari, Chrome, Brave and Morpheus browsers.

You can see the bug on [eduardomataicasa.com](https://eduardomataicasa.com/en/artworks) (by the way thank you for your work !)

![bug_overlay](https://user-images.githubusercontent.com/35377747/125135037-a63dfb80-e108-11eb-84f6-53d65a10fcb3.jpg)

**Comment by sal0max** [comment] 2021-07-16 23:34
Thanks for this bug report.
I took a look into it. This issue is caused by the css of the glightbox library I'm using.

I'll open an issue there to solve this.

PS: That's some awesome artwork!

**Comment by sal0max** [comment] 2021-07-16 23:44
See https://github.com/biati-digital/glightbox/issues/268

**Comment by sal0max** [comment] 2021-08-29 09:51
This issue is now fixed in GLightbox.
I just published an update of this plugin, containing the fix.

**Closed** 2021-09-07 13:25 UTC
Labels: bug
